include: 
  - "https://raw.githubusercontent.com/kinhnv/Platform.Common/main/pipeline/.prepare-ssh.yml"
  - "https://raw.githubusercontent.com/kinhnv/Platform.Common/main/pipeline/.dotnet.yml"

stages:
  - build
  - test
  - deploy

.production_config:
  variables:
    ASPNETCORE_ENVIRONMENT: "Production"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

build:
  stage: build
  variables:
    VERSION: ${CI_PIPELINE_ID}
    DOCKERFILE: ${CI_PROJECT_DIR}/IdentityServer/Dockerfile
    IMAGE: registry.gitlab.com/i3rothers/common/identity-server:${CI_PIPELINE_ID}
  extends:
    - .production_config
    - .dotnet_build

test:
  stage: test
  needs: 
    - build
  tags:
    - shell
  extends:
    - .production_config
  script:
    - echo "test"
        
deploy:
  stage: deploy
  variables:
    VERSION: ${CI_PIPELINE_ID}
    TAG_CONFIG: .servers.identityServer.tag
    VALUE_YAML_FILE: common/values.yaml
  extends:
    - .production_config
    - .dotnet_deploy